import { createContext, useCallback, useContext, useEffect, useState } from "react";
/** English string -> Nepali. Missing keys fall back to the English text. */
const NP = {
    // Nav
    "Browse Rooms": "कोठा खोज्नुहोस्",
    "List Your Room": "कोठा राख्नुहोस्",
    About: "हाम्रोबारे",
    "Get in Touch": "सम्पर्क",
    Favourites: "मनपर्ने",
    Admin: "एडमिन",
    "Sign out": "साइन आउट",
    "Owner sign in": "घरधनी लगइन",
    "Signed out": "साइन आउट भयो",
    "Toggle menu": "मेनु खोल्नुहोस्",
    // Hero
    "Verified rental listings across Nepal": "नेपालभरका प्रमाणित भाडा सूचीहरू",
    "Find a room that": "त्यो कोठा खोज्नुहोस् जुन",
    "feels like home.": "घर जस्तै लाग्छ।",
    "Search affordable rooms, flats and student-friendly rentals by location and budget — then contact the owner directly.": "स्थान र बजेट अनुसार सस्तो कोठा, फ्ल्याट र विद्यार्थीमैत्री भाडा खोज्नुहोस् — त्यसपछि घरधनीलाई सिधै सम्पर्क गर्नुहोस्।",
    Location: "स्थान",
    "Search city, area or keyword...": "सहर, क्षेत्र वा शब्द खोज्नुहोस्...",
    "Max price": "अधिकतम भाडा",
    "Search rooms": "कोठा खोज्नुहोस्",
    "No tenant account required to browse listings or contact owners.": "कोठा हेर्न वा घरधनीलाई सम्पर्क गर्न कुनै खाता आवश्यक छैन।",
    // Home
    "Recently approved": "हालै स्वीकृत",
    "Available rooms right now": "अहिले उपलब्ध कोठाहरू",
    "Preview recently approved rooms. Browse the full listings page for more filters and options.": "हालै स्वीकृत कोठाहरू हेर्नुहोस्। थप फिल्टर र विकल्पका लागि पूरा सूची पृष्ठ खोल्नुहोस्।",
    "Browse all rooms": "सबै कोठा हेर्नुहोस्",
    "No approved listings yet. Be the first.": "अझै कुनै स्वीकृत कोठा छैन। पहिलो बन्नुहोस्।",
    "List a room": "कोठा राख्नुहोस्",
    "How GharKhoj works": "घरखोज कसरी काम गर्छ",
    List: "सूचीकरण",
    "Owners post their room with photos, price, address and contact details.": "घरधनीले फोटो, भाडा, ठेगाना र सम्पर्क विवरणसहित कोठा राख्छन्।",
    Approve: "स्वीकृति",
    "Our admin reviews each listing before it becomes publicly searchable.": "सार्वजनिक हुनु अघि हाम्रो एडमिनले प्रत्येक कोठा जाँच गर्छ।",
    Find: "खोज",
    "Tenants browse, compare and contact the owner directly — no broker required.": "भाडावालाले हेर्छन्, तुलना गर्छन् र घरधनीलाई सिधै सम्पर्क गर्छन् — दलाल चाहिँदैन।",
    "For owners": "घरधनीका लागि",
    "Have a room sitting empty?": "तपाईंको कोठा खाली छ?",
    "List it free. We verify it and put it in front of the students and families already searching your neighbourhood.": "नि:शुल्क राख्नुहोस्। हामी प्रमाणित गरी तपाईंको छिमेकमा खोजिरहेका विद्यार्थी र परिवारसामु पुर्‍याउँछौं।",
    "List your room": "कोठा राख्नुहोस्",
    // Room card
    Verified: "प्रमाणित",
    " / month": " / महिना",
    Details: "विवरण",
    "Add to favourites": "मनपर्नेमा राख्नुहोस्",
    "Remove from favourites": "मनपर्नेबाट हटाउनुहोस्",
    // Search page
    "All listings": "सबै सूची",
    "Browse rooms": "कोठा हेर्नुहोस्",
    "Filter verified rooms by location and budget.": "स्थान र बजेट अनुसार प्रमाणित कोठा छान्नुहोस्।",
    "e.g. Kathmandu": "जस्तै: काठमाडौं",
    "Max price (NPR)": "अधिकतम भाडा (रु)",
    "rooms found": "कोठा भेटिए",
    "room found": "कोठा भेटियो",
    "No rooms found. Try adjusting your filters.": "कुनै कोठा भेटिएन। फिल्टर परिवर्तन गरी हेर्नुहोस्।",
    // Favourites page
    "Saved by you": "तपाईंले सुरक्षित गरेका",
    "Your favourites": "तपाईंका मनपर्ने कोठा",
    "Rooms you tapped the heart on. They stay saved on this device.": "तपाईंले सुरक्षित गरेका कोठाहरू। यी यही उपकरणमा रहन्छन्।",
    "No favourites yet": "अझै कुनै मनपर्ने छैन",
    "Browse rooms and tap the heart on any listing to keep it here for later.": "कोठा हेर्नुहोस् र कुनै पनि सूचीमा बुकमार्क थिचेर यहाँ सुरक्षित राख्नुहोस्।",
    // About page
    "About GharKhoj": "घरखोजबारे",
    "Built from a problem students know too well.": "विद्यार्थीले भोगेको समस्याबाट जन्मिएको।",
    "GharKhoj started with a simple question: why should finding a room near college be this difficult?": "घरखोज एउटा सरल प्रश्नबाट सुरु भयो: कलेज नजिक कोठा खोज्न यति गाह्रो किन हुनुपर्ने?",
    "When I had to search for a room near my college for my studies, the process was much harder than I expected.": "पढाइका लागि कलेज नजिक कोठा खोज्दा यो काम मैले सोचेभन्दा धेरै कठिन भयो।",
    "I had to depend on scattered social-media posts, walk around unfamiliar areas, ask people for contacts, and repeatedly visit rooms that did not match the information I had been given.": "छरिएका सामाजिक सञ्जालका पोस्टमा भर पर्नुपर्‍यो, अपरिचित ठाउँमा घुम्नुपर्‍यो, मान्छेसँग सम्पर्क माग्नुपर्‍यो, र दिइएको जानकारीसँग नमिल्ने कोठा पटक–पटक हेर्न जानुपर्‍यो।",
    "I noticed that many of my friends were facing the same problem. Some rooms were advertised at one price but owners asked for a much higher rent later. In other cases, brokers collected fees but did not genuinely help tenants find a suitable room.": "मेरा धेरै साथीहरू पनि यही समस्यामा थिए। कतिपय कोठा एक भाडामा विज्ञापन गरिन्थ्यो तर पछि घरधनीले धेरै बढी माग्थे। कतै दलालले शुल्क लिए पनि उपयुक्त कोठा खोज्न साँच्चै सहयोग गर्दैनथे।",
    "After looking deeper into the issue, I realized this was not only my problem. Finding trustworthy and affordable rental rooms is difficult for students, newcomers, workers and families across Nepal.": "गहिरो अध्ययन गरेपछि थाहा भयो, यो मेरो मात्र समस्या थिएन। भरपर्दो र किफायती भाडाको कोठा खोज्न नेपालभरका विद्यार्थी, नयाँ आउनेहरू, कामदार र परिवारलाई गाह्रो छ।",
    "That experience became the idea behind GharKhoj: one organized place where tenants can compare approved room listings, see the actual price and location, check the nearest landmark, view photos, and contact the owner directly.": "त्यही अनुभवबाट घरखोजको सोच आयो: एउटै व्यवस्थित ठाउँ जहाँ भाडावालाले स्वीकृत कोठाहरू तुलना गर्न, वास्तविक भाडा र स्थान देख्न, नजिकको ल्यान्डमार्क जाँच्न, फोटो हेर्न र घरधनीलाई सिधै सम्पर्क गर्न सक्छन्।",
    "What we believe": "हाम्रो विश्वास",
    "A home is more than four walls": "घर चार पर्खालभन्दा धेरै हुन्छ",
    "Every listing is reviewed by our team before going live.": "प्रत्येक कोठा सार्वजनिक हुनु अघि हाम्रो टिमले जाँच गर्छ।",
    "No broker fees": "दलाल शुल्क छैन",
    "Tenants connect directly with owners. Always free to browse and contact.": "भाडावाला सिधै घरधनीसँग जोडिन्छन्। हेर्न र सम्पर्क गर्न सधैं नि:शुल्क।",
    "Local first": "स्थानीय पहिले",
    "Built for Nepali cities — neighborhoods, prices, and amenities that actually matter.": "नेपाली सहरका लागि बनेको — साँच्चै महत्त्व राख्ने टोल, भाडा र सुविधाहरू।",
    "Find your next ghar — or help someone find theirs.": "आफ्नो नयाँ घर खोज्नुहोस् — वा अरूलाई खोज्न सघाउनुहोस्।",
    // Contact page
    "Get in touch": "सम्पर्क गर्नुहोस्",
    "We're here to help you find home.": "घर खोज्न हामी तपाईंसँगै छौं।",
    "Questions about a listing, verification, or listing your own room? Send us a message and a real person from the Ghar Khoj team will reply.": "कुनै कोठा, प्रमाणीकरण वा आफ्नो कोठा राख्नेबारे प्रश्न छ? सन्देश पठाउनुहोस्, घरखोज टिमको मानिस आफैं जवाफ दिनेछ।",
    Email: "इमेल",
    Phone: "फोन",
    Office: "कार्यालय",
    Hours: "समय",
    "Sun – Fri, 10am – 6pm": "आइत – शुक्र, बिहान १० – साँझ ६",
    "Jhapa, Nepal": "झापा, नेपाल",
    "Send a message": "सन्देश पठाउनुहोस्",
    "Your name": "तपाईंको नाम",
    "Enter your full name": "पूरा नाम लेख्नुहोस्",
    Subject: "विषय",
    "Question about a listing": "कोठाबारे प्रश्न",
    Message: "सन्देश",
    "Tell us how we can help...": "हामी कसरी सहयोग गर्न सक्छौं लेख्नुहोस्...",
    "Send message": "सन्देश पठाउनुहोस्",
    "Please fill in your name, email and message.": "कृपया नाम, इमेल र सन्देश भर्नुहोस्।",
    "Thanks! We'll get back to you within a day.": "धन्यवाद! हामी एक दिनभित्र सम्पर्क गर्नेछौं।",
    "Common questions": "सामान्य प्रश्नहरू",
    "Answers before you ask.": "सोध्नु अघिका जवाफ।",
    "Is GharKhoj free for tenants?": "घरखोज भाडावालाका लागि नि:शुल्क छ?",
    "Yes. Browsing approved room listings, viewing photos, checking prices and contacting owners directly is completely free for tenants. You never pay a broker fee through GharKhoj.": "हो। स्वीकृत कोठा हेर्न, फोटो देख्न, भाडा जाँच्न र घरधनीलाई सिधै सम्पर्क गर्न भाडावालाका लागि पूर्ण नि:शुल्क छ। घरखोजमा दलाल शुल्क कहिल्यै तिर्नुपर्दैन।",
    "Do tenants need to register?": "भाडावालाले खाता खोल्नुपर्छ?",
    "No account is needed to browse or contact owners. You can save rooms to your favourites using the bookmark icon on each card — those are stored in your browser, so no sign-in is required.": "हेर्न वा घरधनीलाई सम्पर्क गर्न खाता चाहिँदैन। प्रत्येक कार्डको बुकमार्क चिन्हबाट कोठा सुरक्षित राख्न सकिन्छ — यी तपाईंको ब्राउजरमै रहन्छन्, लगइन आवश्यक छैन।",
    "How do property owners list a room?": "घरधनीले कोठा कसरी राख्ने?",
    "Owners head to the “List your room” page, fill in the room details (location, price, photos, landmark, description) and submit. Each listing is reviewed and approved by the GharKhoj team before it appears publicly.": "घरधनी “कोठा राख्नुहोस्” पृष्ठमा जान्छन्, कोठाको विवरण (स्थान, भाडा, फोटो, ल्यान्डमार्क, विवरण) भरी पठाउँछन्। सार्वजनिक हुनु अघि घरखोज टिमले जाँची स्वीकृत गर्छ।",
    "How do I report a fake or misleading listing?": "नक्कली वा भ्रमपूर्ण कोठाबारे कसरी जानकारी दिने?",
    "Use the contact form on this page or email hello@gharkhoj.np with the listing link and what looked wrong. We review every report and remove listings that don’t match their posted information.": "यही पृष्ठको फारम प्रयोग गर्नुहोस् वा कोठाको लिंक र समस्या उल्लेख गरी hello@gharkhoj.np मा इमेल गर्नुहोस्। हामी प्रत्येक उजुरी जाँच्छौं र जानकारीसँग नमिल्ने कोठा हटाउँछौं।",
    // Footer
    "A room rental platform connecting tenants with verified owner listings across Nepal.": "नेपालभरका प्रमाणित घरधनीका कोठासँग भाडावालालाई जोड्ने प्लेटफर्म।",
    Explore: "अन्वेषण",
    "Contact Ghar Khoj": "घरखोजलाई सम्पर्क",
    "Made in Nepal": "नेपालमा बनेको",
};

Object.assign(NP, {
    "Owner Dashboard": "घरधनी ड्यासबोर्ड",
    "For property owners": "घरधनीका लागि",
    "Owner Login": "घरधनी लगइन",
    "Create Owner Account": "घरधनी खाता बनाउनुहोस्",
    "Sign in to manage your room listings.": "आफ्ना कोठा सूची व्यवस्थापन गर्न लगइन गर्नुहोस्।",
    "Create an owner account to list and manage rooms. Tenants do not need an account.": "कोठा राख्न र व्यवस्थापन गर्न घरधनी खाता बनाउनुहोस्। भाडावालालाई खाता चाहिँदैन।",
    "Full Name": "पूरा नाम",
    "Your full name": "तपाईंको पूरा नाम",
    "Phone Number": "फोन नम्बर",
    "District": "जिल्ला",
    "Address": "ठेगाना",
    "Municipality, ward, area": "नगरपालिका, वडा, क्षेत्र",
    "Password": "पासवर्ड",
    "Confirm Password": "पासवर्ड पुष्टि गर्नुहोस्",
    "Forgot Password?": "पासवर्ड बिर्सनुभयो?",
    "Login as Owner": "घरधनीको रूपमा लगइन गर्नुहोस्",
    "Don't have an owner account?": "घरधनी खाता छैन?",
    "Already have an owner account?": "पहिल्यै घरधनी खाता छ?",
    "Create Account": "खाता बनाउनुहोस्",
    "Sign In": "लगइन गर्नुहोस्",
    "Please fill in all fields": "कृपया सबै विवरण भर्नुहोस्।",
    "Password must be at least 8 characters": "पासवर्ड कम्तीमा ८ अक्षरको हुनुपर्छ।",
    "Passwords do not match": "पासवर्डहरू मेल खाएनन्।",
    "After signup, a 6-digit verification code will be sent to your email.": "साइनअपपछि तपाईंको इमेलमा ६ अङ्कको प्रमाणीकरण कोड पठाइनेछ।",
    "Verification code sent to your email.": "प्रमाणीकरण कोड तपाईंको इमेलमा पठाइयो।",
    "Please verify your email before signing in.": "लगइन गर्नु अघि इमेल प्रमाणित गर्नुहोस्।",
    "Welcome back!": "फेरि स्वागत छ!",
    "Verify Your Email": "आफ्नो इमेल प्रमाणित गर्नुहोस्",
    "We've sent a 6-digit verification code to": "हामीले ६ अङ्कको प्रमाणीकरण कोड पठाएका छौं",
    "We've sent a 6-digit verification code to your email.": "हामीले तपाईंको इमेलमा ६ अङ्कको प्रमाणीकरण कोड पठाएका छौं।",
    "Enter the 6-digit code.": "६ अङ्कको कोड लेख्नुहोस्।",
    "Verify Email": "इमेल प्रमाणित गर्नुहोस्",
    "Verify Code": "कोड प्रमाणित गर्नुहोस्",
    "Resend Code": "कोड पुनः पठाउनुहोस्",
    "Resend code in": "कोड पुनः पठाउन",
    "A new verification code has been sent.": "नयाँ प्रमाणीकरण कोड पठाइएको छ।",
    "Email verified successfully.": "इमेल सफलतापूर्वक प्रमाणित भयो।",
    "Back to Owner Login": "घरधनी लगइनमा फर्कनुहोस्",
    "Owner account recovery": "घरधनी खाता पुनःप्राप्ति",
    "Forgot Password": "पासवर्ड बिर्सनुभयो",
    "Email Address": "इमेल ठेगाना",
    "Please enter your registered email.": "कृपया दर्ता गरिएको इमेल लेख्नुहोस्।",
    "Enter the email address associated with your property owner account. We'll send a 6-digit verification code.": "तपाईंको घरधनी खातासँग सम्बन्धित इमेल लेख्नुहोस्। हामी ६ अङ्कको प्रमाणीकरण कोड पठाउनेछौं।",
    "Send Verification Code": "प्रमाणीकरण कोड पठाउनुहोस्",
    "Code expires in 10 minutes.": "कोड १० मिनेटमा समाप्त हुन्छ।",
    "Create New Password": "नयाँ पासवर्ड बनाउनुहोस्",
    "Choose a new password for your GharKhoj owner account.": "आफ्नो घरखोज घरधनी खाताका लागि नयाँ पासवर्ड रोज्नुहोस्।",
    "New Password": "नयाँ पासवर्ड",
    "Confirm New Password": "नयाँ पासवर्ड पुष्टि गर्नुहोस्",
    "Use at least 8 characters.": "कम्तीमा ८ अक्षर प्रयोग गर्नुहोस्।",
    "Reset Password": "पासवर्ड रिसेट गर्नुहोस्",
    "Password Reset Successful": "पासवर्ड सफलतापूर्वक रिसेट भयो",
    "Your password has been changed successfully.": "तपाईंको पासवर्ड सफलतापूर्वक परिवर्तन भयो।",
    "Find Rooms Across Nepal": "नेपालभर कोठा खोज्नुहोस्",
    "Search approved rooms by location, type, rent and facilities.": "स्थान, प्रकार, भाडा र सुविधाअनुसार स्वीकृत कोठा खोज्नुहोस्।",
    "Filters": "फिल्टर",
    "Clear All": "सबै हटाउनुहोस्",
    "Search city, area or landmark...": "सहर, क्षेत्र वा ल्यान्डमार्क खोज्नुहोस्...",
    "Room Type": "कोठाको प्रकार",
    "Any type": "जुनसुकै प्रकार",
    "Maximum Rent (NPR)": "अधिकतम भाडा (रु)",
    "Furnished Status": "फर्निस अवस्थिति",
    "Any": "जुनसुकै",
    "Facilities": "सुविधाहरू",
    "Newest": "नयाँ पहिले",
    "Price Low to High": "कमदेखि बढी भाडा",
    "Price High to Low": "बढीदेखि कम भाडा",
    "Clear Filters": "फिल्टर हटाउनुहोस्",
    "No rooms match your search.": "तपाईंको खोजसँग मिल्ने कोठा भेटिएन।",
    "Available": "उपलब्ध",
    "Single Room": "एकल कोठा",
    "Double Room": "डबल कोठा",
    "Flat": "फ्ल्याट",
    "Apartment": "अपार्टमेन्ट",
    "Hostel Room": "होस्टेल कोठा",
    "House": "घर",
    "Property Information": "सम्पत्ति विवरण",
    "Number of Rooms": "कोठा संख्या",
    "Preferred Tenant": "रुचाइएको भाडावाला",
    "Student": "विद्यार्थी",
    "Family": "परिवार",
    "Working Professional": "कामकाजी व्यक्ति",
    "Anyone": "जो कोही",
    "Floor": "तल्ला",
    "Available From": "उपलब्ध मिति",
    "Security Deposit": "धरौटी",
    "Nearest Landmark": "नजिकको ल्यान्डमार्क",
    "Utility Charges": "सेवा शुल्क",
    "Water": "पानी",
    "Electricity": "बिजुली",
    "Internet": "इन्टरनेट",
    "Included": "समावेश",
    "Separate": "छुट्टै",
    "Property Owner": "घरधनी",
    "Verified Owner": "प्रमाणित घरधनी",
    "Call Owner": "घरधनीलाई फोन गर्नुहोस्",
    "Tenants can contact the owner directly. No tenant login is required.": "भाडावालाले घरधनीलाई सिधै सम्पर्क गर्न सक्छन्। भाडावालाको लगइन आवश्यक छैन।",
    "Report this listing": "यो सूची रिपोर्ट गर्नुहोस्",
    "Reason for report": "रिपोर्टको कारण",
    "Your email (optional)": "तपाईंको इमेल (ऐच्छिक)",
    "Additional details (optional)": "थप विवरण (ऐच्छिक)",
    "Submit Report": "रिपोर्ट पठाउनुहोस्",
    "Thank you. The listing has been reported for review.": "धन्यवाद। यो सूची समीक्षा गर्न रिपोर्ट गरिएको छ।",
    "Back to Search": "खोजमा फर्कनुहोस्",
    "Room not found.": "कोठा भेटिएन।",
    "per month": "प्रति महिना",
    "For owners only": "घरधनीका लागि मात्र",
    "List your room and reach tenants directly.": "आफ्नो कोठा राख्नुहोस् र भाडावालासँग सिधै जोडिनुहोस्।",
    "Create a free owner account, verify your email, add at least five clear room photos and submit your listing for admin approval.": "नि:शुल्क घरधनी खाता बनाउनुहोस्, इमेल प्रमाणित गर्नुहोस्, कम्तीमा पाँच स्पष्ट फोटो थप्नुहोस् र एडमिन स्वीकृतिका लागि सूची पठाउनुहोस्।",
    "Create Owner Account / Login": "घरधनी खाता / लगइन",
    "Owner listing": "घरधनी सूची",
    "List a New Room": "नयाँ कोठा राख्नुहोस्",
    "Edit listing": "सूची सम्पादन",
    "Edit Your Room": "आफ्नो कोठा सम्पादन गर्नुहोस्",
    "Complete the details below. Listings are published only after admin approval.": "तलका विवरण पूरा गर्नुहोस्। एडमिन स्वीकृतिपछि मात्र सूची सार्वजनिक हुन्छ।",
    "1. Basic Information": "१. आधारभूत विवरण",
    "2. Location & Landmark": "२. स्थान र ल्यान्डमार्क",
    "3. Facilities": "३. सुविधाहरू",
    "4. Room Photos": "४. कोठाका फोटो",
    "5. Charges & Availability": "५. शुल्क र उपलब्धता",
    "6. Owner Contact": "६. घरधनी सम्पर्क",
    "Listing Title *": "सूची शीर्षक *",
    "Room Type *": "कोठाको प्रकार *",
    "Monthly Rent (NPR) *": "मासिक भाडा (रु) *",
    "Security Deposit (NPR)": "धरौटी (रु)",
    "Province *": "प्रदेश *",
    "District *": "जिल्ला *",
    "Municipality / City *": "नगरपालिका / सहर *",
    "Ward Number": "वडा नम्बर",
    "Area / Tole *": "क्षेत्र / टोल *",
    "Street": "सडक",
    "Full Address": "पूरा ठेगाना",
    "Nearest Landmark *": "नजिकको ल्यान्डमार्क *",
    "Distance from Landmark *": "ल्यान्डमार्कबाट दूरी *",
    "Attached Bathroom": "अट्याच बाथरूम",
    "Shared Bathroom": "साझा बाथरूम",
    "Kitchen": "भान्सा",
    "Drinking Water": "पिउने पानी",
    "Wi-Fi": "वाइ-फाइ",
    "Bike Parking": "बाइक पार्किङ",
    "Car Parking": "कार पार्किङ",
    "Balcony": "बाल्कोनी",
    "CCTV": "सिसिटिभी",
    "Solar Water": "सोलार पानी",
    "Pet Friendly": "पाल्तु जनावर अनुकूल",
    "24-Hour Water": "२४ घण्टा पानी",
    "Upload at least 5 clear photos. You can add up to 10 photos per listing.": "कम्तीमा ५ स्पष्ट फोटो अपलोड गर्नुहोस्। एक सूचीमा बढीमा १० फोटो राख्न सकिन्छ।",
    "Add Photos": "फोटो थप्नुहोस्",
    "minimum photos added": "न्यूनतम फोटो थपियो",
    "Electricity Charge": "बिजुली शुल्क",
    "Water Charge": "पानी शुल्क",
    "Internet Charge": "इन्टरनेट शुल्क",
    "Preferred Contact": "रुचाइएको सम्पर्क",
    "Show phone publicly": "फोन सार्वजनिक देखाउने",
    "Yes": "हो",
    "No": "होइन",
    "Owner Name": "घरधनीको नाम",
    "Save as Draft": "ड्राफ्टमा राख्नुहोस्",
    "Submit Listing": "सूची पठाउनुहोस्",
    "Save Changes": "परिवर्तन सुरक्षित गर्नुहोस्",
    "Please upload at least 5 room photos.": "कृपया कम्तीमा ५ कोठाका फोटो अपलोड गर्नुहोस्।",
    "Please complete all required room details.": "कृपया सबै आवश्यक कोठा विवरण पूरा गर्नुहोस्।",
    "A listing can contain a maximum of 10 photos.": "एक सूचीमा बढीमा १० फोटो राख्न सकिन्छ।",
    "Welcome back": "फेरि स्वागत छ",
    "Manage your room listings and approval status.": "आफ्ना कोठा सूची र स्वीकृति अवस्था व्यवस्थापन गर्नुहोस्।",
    "Add New Room": "नयाँ कोठा थप्नुहोस्",
    "Total Listings": "कुल सूची",
    "Active Listings": "सक्रिय सूची",
    "Pending Approval": "स्वीकृति बाँकी",
    "Total Views": "कुल हेराइ",
    "Contact Requests": "सम्पर्क अनुरोध",
    "My Listings": "मेरा सूचीहरू",
    "You haven't listed any rooms yet.": "तपाईंले अझै कुनै कोठा राख्नुभएको छैन।",
    "Add Your First Room": "पहिलो कोठा थप्नुहोस्",
    "Views": "हेराइ",
    "Type": "प्रकार",
    "Posted": "राखिएको मिति",
    "Edit": "सम्पादन",
    "Delete": "हटाउनुहोस्",
    "Mark as Rented": "भाडामा गएको चिन्ह लगाउनुहोस्",
    "Submit for Review": "समीक्षाका लागि पठाउनुहोस्",
    "Listing status updated.": "सूची अवस्था अपडेट भयो।",
    "Listing deleted.": "सूची हटाइयो।",
    "Delete this listing permanently?": "यो सूची स्थायी रूपमा हटाउने?",
    "pending": "बाँकी",
    "approved": "स्वीकृत",
    "rejected": "अस्वीकृत",
    "rented": "भाडामा गएको",
    "draft": "ड्राफ्ट",
    "suspended": "निलम्बित",
    "listings": "सूचीहरू",
    "Reach thousands of tenants across Nepal — free.": "नेपालभरका हजारौं भाडावालासम्म नि:शुल्क पुग्नुहोस्।",
    "List your room or flat in minutes. Tenants browse and contact you without signing up — only owners need an account to post and manage listings.": "केही मिनेटमै आफ्नो कोठा वा फ्ल्याट सूचीबद्ध गर्नुहोस्। भाडावालाले साइनअप नगरी हेर्न र सम्पर्क गर्न सक्छन् — सूची राख्न र व्यवस्थापन गर्न घरधनीलाई मात्र खाता चाहिन्छ।",
    "Create owner account": "घरधनी खाता बनाउनुहोस्",
    "List a room now": "अहिले कोठा राख्नुहोस्",
    "See live listings": "सक्रिय सूचीहरू हेर्नुहोस्",
    "Step 1": "चरण १",
    "Step 2": "चरण २",
    "Step 3": "चरण ३",
    "Add photos & details": "फोटो र विवरण थप्नुहोस्",
    "Title, address, rent, deposit, photos. Takes about 5 minutes.": "शीर्षक, ठेगाना, भाडा, धरौटी र फोटो थप्नुहोस्। करिब ५ मिनेट लाग्छ।",
    "Pin location + landmark": "स्थान र ल्यान्डमार्क राख्नुहोस्",
    "Give the full address AND the nearest landmark — temple, school, chowk or hospital. Tenants find it faster.": "पूरा ठेगाना र नजिकको ल्यान्डमार्क — मन्दिर, विद्यालय, चोक वा अस्पताल — राख्नुहोस्। यसले भाडावालालाई छिटो स्थान भेट्न मद्दत गर्छ।",
    "Get approved & live": "स्वीकृत भई सार्वजनिक हुनुहोस्",
    "Our admin team verifies within 24 hours. Then tenants can call or WhatsApp you directly — no broker.": "हाम्रो एडमिन टिमले २४ घण्टाभित्र जाँच गर्छ। त्यसपछि भाडावालाले दलालबिना तपाईंलाई सिधै फोन वा WhatsApp गर्न सक्छन्।",
    "Tenants don't need to sign up": "भाडावालाले साइनअप गर्नुपर्दैन",
    "Browsing, filtering, calling and WhatsApping owners is fully open. Accounts are only required for owners who list properties.": "कोठा हेर्न, फिल्टर गर्न, फोन गर्न र घरधनीलाई WhatsApp गर्न सबैलाई खुला छ। सम्पत्ति सूचीबद्ध गर्ने घरधनीलाई मात्र खाता चाहिन्छ।"
});

const LanguageContext = createContext({ lang: "EN", setLang: () => { }, t: (s) => s });
export const LanguageProvider = ({ children }) => {
    const [lang, setLangState] = useState(() => (typeof localStorage !== "undefined" && localStorage.getItem("gk-lang") === "NP" ? "NP" : "EN"));
    useEffect(() => {
        document.documentElement.lang = lang === "NP" ? "ne" : "en";
    }, [lang]);
    const setLang = useCallback((l) => {
        setLangState(l);
        try {
            localStorage.setItem("gk-lang", l);
        }
        catch {
            /* ignore */
        }
    }, []);
    const t = useCallback((s) => (lang === "NP" ? NP[s] ?? s : s), [lang]);
    return (<LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>);
};
export const useLang = () => useContext(LanguageContext);
