import { Router } from "express";
import { requireAdmin } from "../middleware/auth.js";
import { authLimiter } from "../middleware/rateLimit.js";
import { adminForgotPassword, adminLogin, adminMe, adminResendResetCode, adminResetPassword, adminVerifyResetCode, dashboardStats, deleteRoomAdmin, listMessages, listOwners, listReports, listRoomsAdmin, updateMessage, updateOwnerStatus, updateReport, updateRoomAdmin } from "../controllers/adminController.js";

const router = Router();
router.post("/login", authLimiter, adminLogin);
router.post("/forgot-password", authLimiter, adminForgotPassword);
router.post("/resend-reset-code", authLimiter, adminResendResetCode);
router.post("/verify-reset-code", authLimiter, adminVerifyResetCode);
router.post("/reset-password", authLimiter, adminResetPassword);
router.get("/me", requireAdmin, adminMe);
router.get("/stats", requireAdmin, dashboardStats);
router.get("/rooms", requireAdmin, listRoomsAdmin);
router.patch("/rooms/:id", requireAdmin, updateRoomAdmin);
router.delete("/rooms/:id", requireAdmin, deleteRoomAdmin);
router.get("/owners", requireAdmin, listOwners);
router.patch("/owners/:id/status", requireAdmin, updateOwnerStatus);
router.get("/messages", requireAdmin, listMessages);
router.patch("/messages/:id", requireAdmin, updateMessage);
router.get("/reports", requireAdmin, listReports);
router.patch("/reports/:id", requireAdmin, updateReport);
export default router;
