import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { InputOTP, InputOTPGroup, InputOTPSlot } from "@/components/ui/input-otp";
import { ShieldCheck, Loader2 } from "lucide-react";
import { api, getErrorMessage } from "@/lib/api";
import { toast } from "sonner";

const AdminVerifyResetCode=()=>{const navigate=useNavigate();const email=sessionStorage.getItem("gharkhoj-admin-reset-email")||"";const [code,setCode]=useState("");const [loading,setLoading]=useState(false);const [seconds,setSeconds]=useState(60);useEffect(()=>{if(!email)navigate("/admin/forgot-password",{replace:true});},[email,navigate]);useEffect(()=>{const x=setInterval(()=>setSeconds((s)=>Math.max(0,s-1)),1000);return()=>clearInterval(x)},[]);const submit=async(e)=>{e.preventDefault();if(code.length!==6)return toast.error("Enter the 6-digit code.");setLoading(true);try{const {data}=await api.post("/admin/verify-reset-code",{email,code});sessionStorage.setItem("gharkhoj-admin-reset-token",data.resetToken);navigate("/admin/reset-password");}catch(err){toast.error(getErrorMessage(err));}finally{setLoading(false);}};const resend=async()=>{try{await api.post("/admin/resend-reset-code",{email});setSeconds(60);toast.success("A new verification code has been sent.");}catch(err){toast.error(getErrorMessage(err));}};return <div className="flex min-h-screen items-center justify-center bg-secondary/30 px-4"><form onSubmit={submit} className="w-full max-w-md rounded-3xl border bg-card p-8 text-center" style={{boxShadow:"var(--card-shadow)"}}><ShieldCheck className="mx-auto h-10 w-10 text-primary"/><h1 className="display mt-4 text-3xl">Verify Admin Email</h1><p className="mt-3 text-sm text-muted-foreground">Enter the 6-digit code sent to the admin email.</p><div className="my-7 flex justify-center"><InputOTP maxLength={6} value={code} onChange={setCode} inputMode="numeric"><InputOTPGroup>{[0,1,2,3,4,5].map((i)=><InputOTPSlot key={i} index={i} className="h-12 w-12 text-lg"/>)}</InputOTPGroup></InputOTP></div><Button type="submit" disabled={loading} className="w-full rounded-full font-bold">{loading&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}Verify Code</Button><div className="mt-5 text-sm text-muted-foreground">{seconds?`Resend code in 00:${String(seconds).padStart(2,"0")}`:<button type="button" onClick={resend} className="font-bold text-primary">Resend Code</button>}</div></form></div>};
export default AdminVerifyResetCode;
