import { useEffect } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useQueryClient } from "@tanstack/react-query";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/contexts/AuthContext";
import { useOwnerRooms } from "@/hooks/useRooms";
import { api, getErrorMessage } from "@/lib/api";
import { toast } from "sonner";
import { Loader2, Home, CheckCircle2, Clock, Eye, PhoneCall, Plus, Pencil, Trash2, BedDouble } from "lucide-react";
import { useLang } from "@/contexts/LanguageContext";

const badge=(status)=>({approved:"bg-primary/10 text-primary",pending:"bg-amber-100 text-amber-700",rejected:"bg-destructive/10 text-destructive",rented:"bg-slate-200 text-slate-700",draft:"bg-secondary text-muted-foreground",suspended:"bg-destructive/10 text-destructive"}[status]||"bg-secondary text-muted-foreground");

const OwnerDashboard=()=>{
  const {owner,loading}=useAuth(); const {t}=useLang(); const navigate=useNavigate(); const qc=useQueryClient(); const {data:rooms=[],isLoading}=useOwnerRooms();
  useEffect(()=>{if(!loading&&!owner)navigate("/auth",{replace:true});},[loading,owner,navigate]);
  if(loading||!owner)return <div className="flex min-h-screen items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-primary"/></div>;
  const counts={total:rooms.length,active:rooms.filter((x)=>x.status==="approved").length,pending:rooms.filter((x)=>x.status==="pending").length,views:rooms.reduce((a,x)=>a+(x.views||0),0),contacts:rooms.reduce((a,x)=>a+(x.contactRequests||0),0)};
  const changeStatus=async(id,status)=>{try{await api.patch(`/rooms/${id}/status`,{status});toast.success(t("Listing status updated."));qc.invalidateQueries({queryKey:["owner-rooms"]});}catch(e){toast.error(getErrorMessage(e));}};
  const remove=async(id)=>{if(!confirm(t("Delete this listing permanently?")))return;try{await api.delete(`/rooms/${id}`);toast.success(t("Listing deleted."));qc.invalidateQueries({queryKey:["owner-rooms"]});}catch(e){toast.error(getErrorMessage(e));}};
  return <div className="flex min-h-screen flex-col bg-secondary/20"><Navbar/><main className="container mx-auto flex-1 px-4 py-10"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow mb-2">{t("Owner Dashboard")}</p><h1 className="display text-4xl">{t("Welcome back")}, {owner.fullName}</h1><p className="mt-2 text-muted-foreground">{t("Manage your room listings and approval status.")}</p></div><Link to="/owner/list-room"><Button className="gap-2 rounded-full font-bold"><Plus className="h-4 w-4"/>{t("Add New Room")}</Button></Link></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Stat icon={Home} label={t("Total Listings")} value={counts.total}/><Stat icon={CheckCircle2} label={t("Active Listings")} value={counts.active}/><Stat icon={Clock} label={t("Pending Approval")} value={counts.pending}/><Stat icon={Eye} label={t("Total Views")} value={counts.views}/><Stat icon={PhoneCall} label={t("Contact Requests")} value={counts.contacts}/></div>
    <section className="mt-8"><div className="mb-4 flex items-center justify-between"><h2 className="display text-2xl">{t("My Listings")}</h2><span className="text-sm text-muted-foreground">{rooms.length} {t("listings")}</span></div>{isLoading?<div className="flex justify-center py-16"><Loader2 className="h-7 w-7 animate-spin text-primary"/></div>:rooms.length===0?<div className="soft-card py-16 text-center"><BedDouble className="mx-auto h-10 w-10 text-muted-foreground"/><h3 className="mt-4 text-xl font-extrabold">{t("You haven't listed any rooms yet.")}</h3><Link to="/owner/list-room"><Button className="mt-5 rounded-full">{t("Add Your First Room")}</Button></Link></div>:<div className="space-y-4">{rooms.map((r)=><div key={r.id||r._id} className="soft-card overflow-hidden md:flex"><div className="md:w-52 md:shrink-0"><img src={r.images?.[0]||"/placeholder.svg"} alt={r.title} className="h-44 w-full object-cover md:h-full"/></div><div className="flex flex-1 flex-col p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-xl font-extrabold">{r.title}</h3><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${badge(r.status)}`}>{t(r.status)}</span></div><p className="mt-2 text-sm text-muted-foreground">{[r.area,r.municipality,r.district].filter(Boolean).join(", ")}</p></div><p className="font-extrabold text-primary">NPR {Number(r.monthlyRent||0).toLocaleString("en-NP")}</p></div><div className="mt-4 grid grid-cols-3 gap-3 text-xs text-muted-foreground"><span>{t("Views")}: <strong className="text-foreground">{r.views||0}</strong></span><span>{t("Type")}: <strong className="text-foreground">{t(r.roomType)}</strong></span><span>{t("Posted")}: <strong className="text-foreground">{new Date(r.createdAt).toLocaleDateString()}</strong></span></div><div className="mt-5 flex flex-wrap gap-2"><Link to={`/owner/list-room?edit=${r.id||r._id}`}><Button size="sm" variant="outline" className="gap-2 rounded-full"><Pencil className="h-3.5 w-3.5"/>{t("Edit")}</Button></Link>{r.status==="approved"&&<Button size="sm" variant="outline" onClick={()=>changeStatus(r.id||r._id,"rented")} className="rounded-full">{t("Mark as Rented")}</Button>}{r.status==="draft"&&<Button size="sm" onClick={()=>changeStatus(r.id||r._id,"pending")} className="rounded-full">{t("Submit for Review")}</Button>}<Button size="sm" variant="destructive" onClick={()=>remove(r.id||r._id)} className="ml-auto gap-2 rounded-full"><Trash2 className="h-3.5 w-3.5"/>{t("Delete")}</Button></div></div></div>)}</div>}</section>
  </main><Footer/></div>;
};
const Stat=({icon:Icon,label,value})=><div className="soft-card p-5"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="h-5 w-5"/></span><p className="mt-4 text-3xl font-extrabold">{value}</p><p className="mt-1 text-xs font-semibold text-muted-foreground">{label}</p></div>;
export default OwnerDashboard;
